name: ci

on: [push, pull_request]

jobs:


  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install lammps-interface
      run: |
        pip install -e .[tests]

    - name: Run basic tests
      run: lammps-interface --help

    - name: Run tests
      run: pytest

  windows:
    runs-on: windows-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install lammps-interface
      run: |
        pip install -e .[tests]

    - name: Run basic tests
      shell: cmd
      run: lammps-interface --help

    - name: Run tests
      shell: cmd
      run: pytest

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install lammps-interface
      run: |
        pip install -e .[docs]

    - name: Build docs
      run: cd docs && make html


